DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
  ID VARCHAR,
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  EMAIL_ID VARCHAR,
  AGE VARCHAR,
  GENDER VARCHAR,
  ADDRESS VARCHAR,
  PRIMARY KEY(ID)
);
